app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/rockydb
      username: rockyadmin
      password: 'password'
      pool-size: 30

spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8005
  servlet:
    context-path: /api