export const USER_PERMISSIONS = [
  "READ_USER",
  "CREATE_USER",
  "UPDATE_USER",
  "DELETE_USER",
];
export const ROLE_PERMISSIONS = [
  "READ_ROLE",
  "CREATE_ROLE",
  "UPDATE_ROLE",
  "DELETE_ROLE",
];
export const PERMISSION_PERMISSIONS = [
  "READ_PERMISSION",
  "CREATE_PERMISSION",
  "UPDATE_PERMISSION",
  "DELETE_PERMISSION",
];

export const CUSTOMER_PERMISSIONS = [
  "READ_CUSTOMER",
  "CREATE_CUSTOMER",
  "UPDATE_CUSTOMER",
  "DELETE_CUSTOMER",
];

export const VOLUME_PERMISSIONS = [
  "READ_VOLUME",
  "CREATE_VOLUME",
  "UPDATE_VOLUME",
  "DELETE_VOLUME",
];