export const USER_PERMISSIONS = [
  "READ_USER",
  "CREATE_USER",
  "UPDATE_USER",
  "DELETE_USER",
];
export const ROLE_PERMISSIONS = [
  "READ_ROLE",
  "CREATE_ROLE",
  "UPDATE_ROLE",
  "DELETE_ROLE",
];
export const PERMISSION_PERMISSIONS = [
  "READ_PERMISSION",
  "CREATE_PERMISSION",
  "UPDATE_PERMISSION",
  "DELETE_PERMISSION",
];

export const CUSTOMER_PERMISSIONS = [
  "READ_CUSTOMER",
  "CREATE_CUSTOMER",
  "UPDATE_CUSTOMER",
  "DELETE_CUSTOMER",
];

export const VOLUME_PERMISSIONS = [
  "READ_VOLUME",
  "CREATE_VOLUME",
  "UPDATE_VOLUME",
  "DELETE_VOLUME",
];
export const PRODUCT_TYPE_PERMISSIONS = [
  "READ_PRODUCT_TYPE",
  "CREATE_PRODUCT_TYPE",
  "UPDATE_PRODUCT_TYPE",
  "DELETE_PRODUCT_TYPE",
];

export const PRODUCT_PERMISSIONS = [
  "READ_PRODUCT",
  "CREATE_PRODUCT",
  "UPDATE_PRODUCT",
  "DELETE_PRODUCT",
];

export const GLOBAL_PERMISSIONS = USER_PERMISSIONS.concat(ROLE_PERMISSIONS)
  .concat(PERMISSION_PERMISSIONS)
  .concat(VOLUME_PERMISSIONS)
  .concat(PRODUCT_TYPE_PERMISSIONS)
  .concat(PRODUCT_PERMISSIONS);